name: Terraform GCP Cloud Function

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "**.tf"
      - "function.zip"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="gcp_credentials_json=${{ env.GCP_SA_KEY }}"
        if: github.event_name == 'pull_request'

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve -input=false \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="gcp_credentials_json=${{ env.GCP_SA_KEY }}"
